import Stripe from "stripe";

// Create an isolated Stripe instance for the Finance module
const stripe = new Stripe(process.env.STRIPE_SECRET_KEY, {
    apiVersion: "2025-05-28.basil", // Or match existing version
});

export const stripeFinanceService = {
    /**
     * Retrieve the current Stripe balance (Available and Pending)
     */
    getBalance: async () => {
        return await stripe.balance.retrieve();
    },

    /**
     * Retrieve a list of Stripe Balance Transactions
     * @param {number} limit 
     * @param {string} starting_after 
     */
    getTransactions: async (limit = 10, starting_after = undefined) => {
        const params = { limit };
        if (starting_after) {
            params.starting_after = starting_after;
        }
        return await stripe.balanceTransactions.list(params);
    },

    /**
     * Retrieve a list of Payouts from Stripe
     * @param {number} limit 
     * @param {string} starting_after 
     */
    getPayouts: async (limit = 10, starting_after = undefined) => {
        const params = { limit };
        if (starting_after) {
            params.starting_after = starting_after;
        }
        return await stripe.payouts.list(params);
    },

    /**
     * Create a new Payout
     * @param {number} amountInCents 
     * @param {string} currency 
     */
    createPayout: async (amountInCents, currency = "usd") => {
        return await stripe.payouts.create({
            amount: amountInCents,
            currency,
        });
    },

    /**
     * Retrieve attached external bank accounts (for the platform account itself)
     * For a single account, this usually requires an Account ID. If no account ID is passed, 
     * this method retrieves the platform account details and then its external accounts.
     */
    getBankAccounts: async () => {
        const account = await stripe.accounts.retrieve();
        if(!account || !account.id) {
            throw new Error("Could not retrieve Stripe platform account.");
        }
        return await stripe.accounts.listExternalAccounts(account.id, {
            object: "bank_account",
            limit: 10,
        });
    },

    /**
     * Attach a new external bank account to the platform Stripe account
     * @param {string} bankAccountToken - Token generated by Stripe Elements on frontend
     */
    attachBankAccount: async (bankAccountToken) => {
        const account = await stripe.accounts.retrieve();
        return await stripe.accounts.createExternalAccount(account.id, {
            external_account: bankAccountToken,
        });
    },

    /**
     * Remove an external bank account
     * @param {string} bankAccountId 
     */
    removeBankAccount: async (bankAccountId) => {
        const account = await stripe.accounts.retrieve();
        return await stripe.accounts.deleteExternalAccount(account.id, bankAccountId);
    },

    /**
     * Set a bank account as default for payouts
     * @param {string} bankAccountId 
     */
    setDefaultBankAccount: async (bankAccountId) => {
        const account = await stripe.accounts.retrieve();
        return await stripe.accounts.updateExternalAccount(account.id, bankAccountId, {
            default_for_currency: true,
        });
    }
};
